categories:
  Assetic:
    label: Assetic Configuration
  Assetic.general:
    label: General
    parent: Assetic
  Assetic.livereload:
    label: LiveReload
    parent: Assetic

settings:
  assetic.settings.development:
    type: bool
    default: false
    label: Development mode
    description: Always re-compile assets
    category: Assetic.general

  assetic.settings.createSymlink:
    type: bool
    default: false
    label: Symlink
    description: Always create a symlink to the compiled file
    category: Assetic.general

  assetic.settings.allowCompileWithoutLogin:
    type: bool
    default: false
    label: Compile if no backend user is logged in
    description: ""
    category: Assetic.general

  assetic.settings.strict:
    type: bool
    default: false
    label: Strict mode
    description: Throw exceptions for missing filter functions
    category: Assetic.general

  assetic.settings.livereload.addJavascript:
    type: bool
    default: false
    label: Add LiveReload JavaScript
    description: ""
    category: Assetic.livereload

  assetic.settings.livereload.port:
    type: int
    default: 35729
    label: LiveReload port
    description: ""
    category: Assetic.livereload

  assetic.settings.livereload.skipServerTest:
    type: bool
    default: false
    label: Skip LiveReload test connection
    description: ""
    category: Assetic.livereload
